### ISSUE TITLE
Videos not being edited

### ISSUE THREAD

**Issue by gigz-afk** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#10]
Hey

My videos are not uploaded to YT and it won’t let me do a manual export. I’m using local host for my setup (windows) and I’m wondering how can I get my videos edited and where can I see the process.

Thanks

**Comment by IReallyHateSoftware** [comment]
Yeah, I am having the same issue. I want to export the videos myself, no need for the bot do to it automatically, I would like to make some adjustments beforehand. But the "Manual Export" button does not thing. It doesn't generate any sort of errors in any of the opened shells, so I am not sure if it is even coded, can we have a clarification on that?

Bonus: When I hit the "Add Script" I get an error, but I also do not know what you're supposed to write on the "Enter Script URL below" or if it is really needed.

**Comment by stratosphere55** [comment]
It this is your first time dealing with python this bot might not be for you. It's a great bot once working but it takes alot of knowledge about python, MySQL and command line to get working how you want. Most of your issues are fixed by simply reading the code and debugging.

**Comment by HA6Bots** [comment]
Manual export button does not work and does nothing, please just set the setting in video generator config file to exportoffline true.

**Comment by IReallyHateSoftware** [comment]
Hello HA6Bots (Thomas),
I have already done that, which actually does not reflect the code on settings.py for some reason, and even setting in there to "exportOffline = True" does not do anything. Although to be honest with you, I was expecting for the Manual Export button to enable the functionality, but with what you've just wrote; after making this setting; what should done to export the file manually? Click on "Send to Video Generator"?

**Comment by IReallyHateSoftware** [comment]
When I try to manually export, I get this, after the video is sent (successfully) the Videoqueue (Videoqueue\rawsaves)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "path\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "path\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "path\Youtube Bot Video Generator\youtubequeue.py", line 106, in tickThread
    script.renderVideo()
  File "path\Youtube Bot Video Generator\videoscript.py", line 55, in renderVideo
    export_location = newMovie.renderVideo()
  File "path\Youtube Bot Video Generator\generatemovie.py", line 26, in renderVideo
    clips = self.videoformat.renderClips(self.content, self.title)
  File "path\Youtube Bot Video Generator\VideoTypes\standardredditformat.py", line 239, in renderClips
    fontSizeInfo = self.calculateFontSize(subcontent, 100)
  File "path\Youtube Bot Video Generator\VideoTypes\standardredditformat.py", line 159, in calculateFontSize
    font = ImageFont.truetype(fontpath, fontSize - timesLooped)
  File "path\Python\lib\site-packages\PIL\ImageFont.py", line 642, in truetype
    return freetype(font)
  File "path\Python\lib\site-packages\PIL\ImageFont.py", line 639, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "\pathPython\lib\site-packages\PIL\ImageFont.py", line 188, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

Any ideas what it might be?

**Comment by HA6Bots** [comment]
You are missing some of the font files. Please download the assets folder I have provided and drag the assets directory into you video generator and client.

**Comment by HA6Bots** [comment]
Let me know if this has solved your problem so I can close this.

**Comment by IReallyHateSoftware** [comment]
Okay that fixed /that/ problem, I didn't know you should put the asset folder in the video generator, too.
So right now it builds (renders) the text in to images, it is throwing wine errors, but I am guessing that's normal since I am not on Linux.

However, now there is another issue, it cannot format any of the clips:

Formatting clip (1/12)
[Errno 2] No such file or directory: 'Path/Youtube Bot Video Generator/Temp/tempaudio1.wav'
[Errno 2] No such file or directory: 'Path/Youtube Bot Video Generator/Temp/tempaudio2.wav'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "I:\b\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "I:\b\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "Path\Youtube Bot Video Generator\youtubequeue.py", line 106, in tickThread
    script.renderVideo()
  File "Path\Youtube Bot Video Generator\videoscript.py", line 55, in renderVideo
    export_location = newMovie.renderVideo()
  File "Path\Youtube Bot Video Generator\generatemovie.py", line 27, in renderVideo
    self.videoformat.createMovie(clips, self)
  File "Path\Youtube Bot Video Generator\VideoTypes\standardredditformat.py", line 342, in createMovie
    movie.addFrameWithTransitionAndPause(image_path, audio_path, "%s/Intervals/standard.mp4" % settings.assetPath, 1000)  File "Path\Youtube Bot Video Generator\generatemovie.py", line 153, in addFrameWithTransitionAndPause
    f = sf.SoundFile(audio_file)
  File "Path\Python\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "Path\Python\lib\site-packages\soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "Path\Python\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'Path\\Youtube Bot Video Generator/Temp/tempaudio3.wav': System error.

I tried to place some sample files "tempaudio#" in the temp folder and it ran them, but obviously everything after that was blank, however video finished processing (without any audio but the sample). So I think this is the final error for me.

Appreciate all your help thus far, mate!

**Comment by HA6Bots** [comment]
Have you created a folder called /Temp/ in your directory?

**Comment by IReallyHateSoftware** [comment]
Yes, the images get stored there before being processed. As I have mentioned, I placed some temp .wav files in there, completely unrelated to the vids, named them "tempaudio#.wav" and it worked. So I am a bit stumped.

![Untitled-1](https://user-images.githubusercontent.com/61717731/75828304-343b0100-5db4-11ea-8b8b-2a646ce33e61.jpg)

**Comment by IReallyHateSoftware** [comment]
I think I managed to get a bit further. On the standardredditformat.py, line 342 (which is in the error) there are missing brackets in the settings.assetPath statement. I placed them, but the argument becomes wrong after that. 

  File "Path\Youtube Bot Video Generator\VideoTypes\standardredditformat.py", line 342, in createMovie
    movie.addFrameWithTransitionAndPause(image_path, audio_path, "%s/Intervals/standard.mp4" % (settings.assetPath, 1000))
TypeError: not all arguments converted during string formatting

I tried removing the pause function, and the video gets processed but without any audio, as it cannot generate it. No errors are given besides the below, so do not know where the problem with the audio creation is coming from.
[Errno 2] No such file or directory: Youtube Bot Video Generator/Temp/tempaudio1.wav'
[Errno 2] No such file or directory: Youtube Bot Video Generator/Temp/tempaudio2.wav'
[Errno 2] No such file or directory: Youtube Bot Video Generator/Temp/tempaudio3.wav'
[Errno 2] No such file or directory: Youtube Bot Video Generator/Temp/tempaudio4.wav'
...

**Comment by IReallyHateSoftware** [comment]
I made it work, you can close this one.

**Comment by Dexu5** [comment]
@IReallyHateSoftware Hey, I'm facing the same issue on line 342 for standardredditformat.py
Could you help me what made your code work post that?

**Comment by pidthekid** [comment]
Hey @IReallyHateSoftware , I'm also having the same issue on line 342 for standardredditformat.py and it seems @Dexu5 is too.  Could you please advise on this? Would be real helpful, thanks.
