### ISSUE TITLE
VidGen Error

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#19]
Can you help me understand what it needs me to do and why the -t keeps spamming on my shell? Thank you so much

`'-t' is not recognized as an internal or external command,
operable program or batch file.
'-t' is not recognized as an internal or external command,
operable program or batch file.
'-t' is not recognized as an internal or external command,
operable program or batch file.
'-t' is not recognized as an internal or external command,
operable program or batch file.
'-t' is not recognized as an internal or external command,
operable program or batch file.
Formatting clip (1/7)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\youtubequeue.py", line 106, in tickThread
    script.renderVideo()
  File "C:\Users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator\videoscript.py", line 55, in renderVideo
    export_location = newMovie.renderVideo()
  File "C:\Users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator\generatemovie.py", line 27, in renderVideo
    self.videoformat.createMovie(clips, self)
  File "C:\Users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator\VideoTypes\standardredditformat.py", line 342, in createMovie
    movie.addFrameWithTransitionAndPause(image_path, audio_path, "%s/Intervals/standard.mp4" % settings.assetPath, 1000)  File "C:\Users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator\generatemovie.py", line 153, in addFrameWithTransitionAndPause
    f = sf.SoundFile(audio_file)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'C:\\Users\\marcu\\desktop\\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\\Youtube Bot Video Generator/Temp/tempaudio1.wav': System error.
`

**Comment by HA6Bots** [comment]
Try add balcon.exe to system path and then where it says balcon_location just put "balcon"
