### ISSUE TITLE
Error using Linux 

### ISSUE THREAD

**Issue by zRattly** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#22]
```
Error: voice not selected
0041:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0041:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0041:err:ole:CoGetClassObject class {cb96b400-c743-11cd-80e5-00aa003e4b50} not registered
0041:err:ole:CoGetClassObject class {cb96b400-c743-11cd-80e5-00aa003e4b50} not registered
0041:err:ole:create_server class {cb96b400-c743-11cd-80e5-00aa003e4b50} not registered
0041:err:ole:CoGetClassObject no class object {cb96b400-c743-11cd-80e5-00aa003e4b50} could be created for context 0x7
``` 
spams in console in loop
If i ignore that, I get an error in console at the end

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "youtubequeue.py", line 106, in tickThread
    script.renderVideo()
  File "/root/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/videoscript.py", line 55, in renderVideo
    export_location = newMovie.renderVideo()
  File "/root/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/generatemovie.py", line 27, in renderVideo
    self.videoformat.createMovie(clips, self)
  File "/root/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/VideoTypes/standardredditformat.py", line 342, in createMovie
    movie.addFrameWithTransitionAndPause(image_path, audio_path, "%s/Intervals/standard.mp4" % settings.assetPath, 1000)
  File "/root/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/generatemovie.py", line 153, in addFrameWithTransitionAndPause
    f = sf.SoundFile(audio_file)
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/root/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/Temp/tempaudio1.wav': System error.
```

**Comment by zRattly** [comment]
How do i get Daniel voice working in linux? Tryed everything

**Comment by zRattly** [comment]
found the error - need to install the voice
