### ISSUE TITLE
AbsoluteError

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#25]
Hey, how am I able to fix this? Thanks

`Putting together clip (3/27)
Putting together clip (4/27)
Putting together clip (5/27)
Putting together clip (6/27)
Putting together clip (7/27)
Putting together clip (8/27)
Putting together clip (9/27)
Putting together clip (10/27)
Putting together clip (11/27)
Putting together clip (12/27)
Putting together clip (13/27)
Putting together clip (14/27)
Putting together clip (15/27)
Putting together clip (16/27)
Putting together clip (17/27)
Putting together clip (18/27)
Putting together clip (19/27)
Putting together clip (20/27)
Putting together clip (21/27)
Putting together clip (22/27)
Putting together clip (23/27)
Putting together clip (24/27)
Putting together clip (25/27)
Putting together clip (26/27)
Putting together clip (27/27)
Generating Audio Loop (532.9394557823128)
Using Audio Loop C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator/Assets/Music/Funny/funny28.mp3
MoviePy - Writing audio in C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator/Temp/music-loop.wav
chunk:   0%|                                                                       | 0/11731 [00:00<?, ?it/s, now=None]Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\youtubequeue.py", line 106, in tickThread
    script.renderVideo()
  File "C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator\videoscript.py", line 55, in renderVideo
    export_location = newMovie.renderVideo()
  File "C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\Youtube Bot Video Generator\generatemovie.py", line 70, in renderVideo
    music_loop.to_audiofile("%s/music-loop.wav" % settings.tempPath)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\tools.py", line 137, in fdepr
    return f(*a, **kw)
  File "<decorator-gen-45>", line 2, in write_audiofile
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 210, in write_audiofile
    logger=logger)
  File "<decorator-gen-9>", line 2, in ffmpeg_audiowrite
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 169, in ffmpeg_audiowrite
    logger=logger):
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 86, in iter_chunks
    fps=fps, buffersize=chunksize)
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 127, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 297, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 298, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\fx\volumex.py", line 19, in <lambda>
    return clip.fl(lambda gf, t: factor * gf(t),
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 77, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\io\readers.py", line 185, in get_frame
    self.buffer_around(fr_max)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\io\readers.py", line 239, in buffer_around
    array = self.read_chunk(chunksize)
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\audio\io\readers.py", line 113, in read_chunk
    s = self.proc.stdout.read(L)
AttributeError: 'NoneType' object has no attribute 'stdout'
`

**Comment by HA6Bots** [comment]
Seems to be an issue with moviepy. Are you using moviepy version 1.0.0?
