### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#26]
What needs to be done for this?

`Found raw save for script 36
Found raw save for script 6
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\marcu\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\YouTube Bot Client\manualreview\client.py", line 241, in serverResponseListen
    parseScripts(data)
  File "C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\YouTube Bot Client\manualreview\client.py", line 182, in parseScripts
    commentInformation=newscript, music_type="funny", status=status, editedby=editedby, commentsamount=comments_amount)
  File "C:\users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\YouTube Bot Client\manualreview\videoscriptcore.py", line 39, in __init__
    script = pickle.load(pickle_file)
EOFError: Ran out of input`

**Comment by HA6Bots** [comment]
Seems like there was an error with getting data from the database. I suggest googling the problem with mysql-python (or whatever python mysql module you have installed), maybe some kind of default restriction on the size of data being downloaded from MySQL. Is this a problem for all scripts or just this one in particular?
