### ISSUE TITLE
invalid literal for int() with base 10: b'J\x00\x00\x00\n8.0.2' for msglen = int(buf[:HEADERSIZE])

### ISSUE THREAD

**Issue by DonnyRedZone** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#51]
C:\Users\Donov\PycharmProjects\pythonProject5\venv\Scripts\python.exe "C:/Users/Donov/PycharmProjects/pythonProject5/Youtube Bot Client/init.py"
Found config in location C:\Users\Donov\PycharmProjects\pythonProject5\Youtube Bot Client\config.ini
connecting to localhost port 10000
Client listen thread active
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Donov\PycharmProjects\pythonProject5\Youtube Bot Client\client.py", line 239, in serverResponseListen
    msglen = int(buf[:HEADERSIZE])
ValueError: invalid literal for int() with base 10: b'J\x00\x00\x00\n8.0.2'
Socket Broken!
2020-11-25 17:00:58.680502 CLIENT sending ping

Then a login window opens and I put in my details and it says

2020-11-25 17:00:58.680502 CLIENT sending ping
Socket Broken

**Comment by DonnyRedZone** [comment]
For anyone whos interested , there were 2 issues causing this

My terrible setup - pls know anything that says "Server" in the config files and settings.py's is NOT the mysql server and should all  be the same thing that is not the the same one as a the mysql server and anything that says "database" should match what youve setup with mysql

Having no users in the database to login to , could not for the life of me find out how to add a user , ill scrubbed through all the code and found an unused add user function then using the code in that function I manually added a user using the script thingy in my sql 

query = "INSERT INTO users(username, password) " \
            "VALUES(%s, %s)"

in sql i said INSERT INTO users("username","a md5 version of your password") and that sucsessfully gave me a user to login to and fixed the socket broken error so enjoy 👍
