### ISSUE TITLE
issue with youtubequeue.py Creds

### ISSUE THREAD

**Issue by asathish02** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#55]
Having an issue where I am unable to run the youtubequeue.py successfully. here is the issue below:

(base) C:\Users\Abhinav\PycharmProjects\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\Youtube Bot Video Generator>python youtubequeue.py
C:\Users\Abhinav\PycharmProjects\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\Youtube Bot Video Generator/Creds/client_secrets.json
Found config.ini
Found Temp Path
Found Assets Path
found Verdana.ttf
C:\Users\Abhinav\anaconda3\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Found config.ini
Found Temp Path
Found Assets Path
found Verdana.ttf
Traceback (most recent call last):
  File "C:\Users\Abhinav\anaconda3\lib\site-packages\oauth2client\clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Abhinav\\PycharmProjects\\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\\Youtube Bot Video Generator/Creds/client_secrets.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "youtubequeue.py", line 205, in <module>
    videouploader.get_credentials()
  File "C:\Users\Abhinav\PycharmProjects\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\Youtube Bot Video Generator\videouploader.py", line 31, in get_credentials
    flow = client.flow_from_clientsecrets(settings.google_cred_upload, 'https://www.googleapis.com/auth/youtube.upload')
  File "C:\Users\Abhinav\anaconda3\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Abhinav\anaconda3\lib\site-packages\oauth2client\client.py", line 2134, in flow_from_clientsecrets
    client_type, client_info = clientsecrets.loadfile(filename,
  File "C:\Users\Abhinav\anaconda3\lib\site-packages\oauth2client\clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "C:\Users\Abhinav\anaconda3\lib\site-packages\oauth2client\clientsecrets.py", line 124, in _loadfile
    raise InvalidClientSecretsError('Error opening file', exc.filename,
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'C:\\Users\\Abhinav\\PycharmProjects\\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\\Youtube Bot Video Generator/Creds/client_secrets.j
son', 'No such file or directory', 2)

**Comment by HA6Bots** [comment]
Try setting exportOffline=true in the video generator config.
